import { TableSchema, TableDefinition, ColumnDefinition, ColumnType } from './table';
import { z } from 'zod';

export class SchemaRegistry {
  private tables = new Map<string, TableSchema>();
  private relationships = new Map<string, Relationship[]>();
  private validators = new Map<string, z.ZodSchema<any>>();
  private initialized = false;

  constructor() {
    this.initializeSystemTables();
  }

  private initializeSystemTables(): void {
    // Create migrations table for tracking schema changes
    const migrationsTable = new TableSchema({
      name: '_forma_migrations',
      columns: {
        id: {
          type: 'serial',
          primaryKey: true
        },
        version: {
          type: 'varchar',
          length: 50,
          unique: true,
          nullable: false
        },
        name: {
          type: 'varchar',
          length: 255,
          nullable: false
        },
        applied_at: {
          type: 'timestamptz',
          default: 'NOW()',
          nullable: false
        },
        checksum: {
          type: 'varchar',
          length: 64,
          nullable: false
        },
        execution_time: {
          type: 'integer',
          comment: 'Execution time in milliseconds'
        },
        success: {
          type: 'boolean',
          default: true
        },
        error_message: {
          type: 'text',
          nullable: true
        }
      },
      indexes: [
        {
          columns: ['version'],
          unique: true
        },
        {
          columns: ['applied_at']
        }
      ],
      comment: 'Forma internal migrations tracking table'
    });

    this.tables.set('_forma_migrations', migrationsTable);
  }

  register(table: TableSchema): this {
    const name = table.definition.name;
    
    if (this.tables.has(name)) {
      throw new Error(`Table '${name}' is already registered`);
    }
    
    // Validate table definition
    const errors = this.validateTableDefinition(table.definition);
    if (errors.length > 0) {
      throw new Error(`Invalid table definition for '${name}':\n${errors.join('\n')}`);
    }
    
    this.tables.set(name, table);
    this.createValidator(table);
    this.detectRelationships(table);
    
    return this;
  }

  registerFromDefinitions(definitions: TableDefinition[]): this {
    for (const definition of definitions) {
      const table = new TableSchema(definition);
      this.register(table);
    }
    return this;
  }

  unregister(tableName: string): boolean {
    // Remove relationships involving this table
    for (const [source, rels] of this.relationships.entries()) {
      this.relationships.set(
        source,
        rels.filter(rel => rel.targetTable !== tableName && rel.sourceTable !== tableName)
      );
    }
    this.relationships.delete(tableName);
    
    this.validators.delete(tableName);
    return this.tables.delete(tableName);
  }

  getTable(name: string): TableSchema | undefined {
    return this.tables.get(name);
  }

  getTableStrict(name: string): TableSchema {
    const table = this.tables.get(name);
    if (!table) {
      throw new Error(`Table '${name}' not found in registry`);
    }
    return table;
  }

  hasTable(name: string): boolean {
    return this.tables.has(name);
  }

  getAllTables(): TableSchema[] {
    return Array.from(this.tables.values());
  }

  getTableNames(): string[] {
    return Array.from(this.tables.keys());
  }

  getRelationships(tableName: string): Relationship[] {
    return this.relationships.get(tableName) || [];
  }

  getOutgoingRelationships(tableName: string): Relationship[] {
    return this.getRelationships(tableName).filter(rel => rel.sourceTable === tableName);
  }

  getIncomingRelationships(tableName: string): Relationship[] {
    return this.getRelationships(tableName).filter(rel => rel.targetTable === tableName);
  }

  getForeignKeyRelationships(tableName: string): Relationship[] {
    return this.getRelationships(tableName).filter(rel => 
      rel.type === 'foreign-key' && rel.sourceTable === tableName
    );
  }

  // TypeScript type generation
  generateTypeScript(): string {
    const imports = `// Generated by Forma Schema Registry
// DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}

export type Timestamp = Date | string;
export type JSONValue = string | number | boolean | null | JSONValue[] | { [key: string]: JSONValue };
export type UUID = string;
`;

    const types: string[] = [imports];
    
    for (const table of this.getAllTables()) {
      if (table.definition.name.startsWith('_')) {
        continue; // Skip internal tables
      }
      
      const interfaceName = this.toPascalCase(table.definition.name);
      const properties: string[] = [];
      
      for (const [columnName, column] of Object.entries(table.definition.columns)) {
        const tsType = this.toTypeScriptType(column.type, column.nullable);
        const optional = column.nullable ? '?' : '';
        properties.push(`  ${columnName}${optional}: ${tsType};`);
        
        if (column.comment) {
          properties[properties.length - 1] += ` // ${column.comment}`;
        }
      }
      
      types.push(`export interface ${interfaceName} {`);
      types.push(...properties);
      types.push('}\n');
      
      // Insert type (without auto-generated primary keys)
      const autoGeneratedPks = table.getPrimaryKey()
        .filter(pk => {
          const column = table.definition.columns[pk];
          return column.autoIncrement || column.default?.includes('gen_random_uuid') || column.default?.includes('uuid_generate');
        });
      
      if (autoGeneratedPks.length > 0) {
        types.push(`export type Insert${interfaceName} = Omit<${interfaceName}, ${autoGeneratedPks.map(pk => `'${pk}'`).join(' | ')}> & Partial<Pick<${interfaceName}, ${autoGeneratedPks.map(pk => `'${pk}'`).join(' | ')}>>;\n`);
      } else {
        types.push(`export type Insert${interfaceName} = Partial<${interfaceName}>;\n`);
      }
      
      // Update type
      types.push(`export type Update${interfaceName} = Partial<${interfaceName}> & {`);
      types.push(`  ${table.getPrimaryKey().map(pk => `${pk}: ${this.toTypeScriptType(table.definition.columns[pk].type, false)}`).join(';\n  ')}`);
      types.push('};\n');
      
      // Where type
      types.push(`export type ${interfaceName}Where = {`);
      for (const [columnName, column] of Object.entries(table.definition.columns)) {
        const tsType = this.toTypeScriptType(column.type, true);
        types.push(`  ${columnName}?: ${tsType} | {`);
        types.push(`    eq?: ${tsType};`);
        types.push(`    neq?: ${tsType};`);
        if (column.type === 'integer' || column.type === 'bigint' || column.type === 'float' || column.type === 'decimal' || column.type === 'numeric') {
          types.push(`    gt?: ${tsType};`);
          types.push(`    gte?: ${tsType};`);
          types.push(`    lt?: ${tsType};`);
          types.push(`    lte?: ${tsType};`);
        }
        if (column.type === 'string' || column.type === 'text' || column.type === 'varchar') {
          types.push(`    like?: string;`);
          types.push(`    ilike?: string;`);
          types.push(`    contains?: string;`);
          types.push(`    startsWith?: string;`);
          types.push(`    endsWith?: string;`);
        }
        types.push(`    in?: ${tsType}[];`);
        types.push(`    nin?: ${tsType}[];`);
        if (column.nullable) {
          types.push(`    is?: ${tsType} | null;`);
          types.push(`    isNot?: ${tsType} | null;`);
        }
        types.push(`  };`);
      }
      types.push(`  AND?: ${interfaceName}Where[];`);
      types.push(`  OR?: ${interfaceName}Where[];`);
      types.push(`  NOT?: ${interfaceName}Where;`);
      types.push('};\n');
    }
    
    return types.join('\n');
  }

  // Migration generation
  generateMigrationSQL(options: {
    includeDrop?: boolean;
    includeIndexes?: boolean;
    includeComments?: boolean;
  } = {}): string {
    const defaults = {
      includeDrop: false,
      includeIndexes: true,
      includeComments: true
    };
    const config = { ...defaults, ...options };
    
    const statements: string[] = [
      '-- Forma Migration SQL',
      `-- Generated at: ${new Date().toISOString()}`,
      '-- DO NOT EDIT MANUALLY',
      ''
    ];
    
    // Filter out internal tables
    const userTables = this.getAllTables().filter(table => !table.definition.name.startsWith('_'));
    
    if (config.includeDrop) {
      // Generate DROP statements in reverse order (to handle dependencies)
      for (let i = userTables.length - 1; i >= 0; i--) {
        const table = userTables[i];
        statements.push(`DROP TABLE IF EXISTS ${this.quoteIdentifier(table.definition.name)} CASCADE;`);
      }
      statements.push('');
    }
    
    // Generate CREATE TABLE statements
    for (const table of userTables) {
      statements.push(table.toSQL(config.includeIndexes, config.includeComments));
      statements.push('');
    }
    
    return statements.join('\n');
  }

  generateDiffSQL(targetRegistry: SchemaRegistry): string {
    const currentTables = new Set(this.getTableNames().filter(name => !name.startsWith('_')));
    const targetTables = new Set(targetRegistry.getTableNames().filter(name => !name.startsWith('_')));
    
    const statements: string[] = [
      '-- Forma Schema Diff',
      `-- Generated at: ${new Date().toISOString()}`,
      '-- Migrates from current schema to target schema',
      ''
    ];
    
    // Tables to drop
    const tablesToDrop = [...currentTables].filter(table => !targetTables.has(table));
    for (const tableName of tablesToDrop) {
      statements.push(`DROP TABLE IF EXISTS ${this.quoteIdentifier(tableName)} CASCADE;`);
    }
    
    if (tablesToDrop.length > 0) {
      statements.push('');
    }
    
    // Tables to create or alter
    for (const tableName of targetTables) {
      const targetTable = targetRegistry.getTableStrict(tableName);
      
      if (!currentTables.has(tableName)) {
        // Create new table
        statements.push(targetTable.toSQL(true, true));
      } else {
        // Alter existing table
        const currentTable = this.getTableStrict(tableName);
        const alterStatements = this.generateAlterTableSQL(currentTable, targetTable);
        if (alterStatements) {
          statements.push(alterStatements);
        }
      }
      statements.push('');
    }
    
    return statements.join('\n');
  }

  // Validation
  validate(): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];
    
    // Validate all tables
    for (const table of this.getAllTables()) {
      if (table.definition.name.startsWith('_')) {
        continue;
      }
      
      // Check for circular references
      const circularRefs = this.detectCircularReferences(table.definition.name);
      if (circularRefs.length > 0) {
        errors.push(`Circular reference detected for table '${table.definition.name}': ${circularRefs.join(' -> ')}`);
      }
      
      // Validate foreign keys
      for (const [columnName, column] of Object.entries(table.definition.columns)) {
        if (column.references) {
          const refTable = this.tables.get(column.references.table);
          if (!refTable) {
            errors.push(`Table '${table.definition.name}.${columnName}' references non-existent table '${column.references.table}'`);
          } else if (!refTable.definition.columns[column.references.column]) {
            errors.push(`Table '${table.definition.name}.${columnName}' references non-existent column '${column.references.table}.${column.references.column}'`);
          }
        }
      }
      
      // Check for missing indexes on foreign keys
      const foreignKeyColumns = Object.entries(table.definition.columns)
        .filter(([_, col]) => col.references)
        .map(([name]) => name);
      
      const indexes = table.definition.indexes || [];
      for (const fkColumn of foreignKeyColumns) {
        const hasIndex = indexes.some(idx => idx.columns.includes(fkColumn));
        if (!hasIndex) {
          warnings.push(`Foreign key column '${table.definition.name}.${fkColumn}' is not indexed (performance issue)`);
        }
      }
    }
    
    return {
      valid: errors.length === 0,
      errors,
      warnings
    };
  }

  // Export/Import
  export(): SchemaExport {
    const tables: TableDefinition[] = [];
    const relationships: Relationship[] = [];
    
    for (const table of this.getAllTables()) {
      if (!table.definition.name.startsWith('_')) {
        tables.push(table.definition);
      }
    }
    
    for (const [_, rels] of this.relationships) {
      relationships.push(...rels);
    }
    
    return {
      version: '1.0',
      exportedAt: new Date().toISOString(),
      tables,
      relationships: [...new Map(relationships.map(r => [r.id, r])).values()]
    };
  }

  import(data: SchemaExport, options: { overwrite?: boolean } = {}): void {
    if (data.version !== '1.0') {
      throw new Error(`Unsupported schema version: ${data.version}`);
    }
    
    // Clear existing tables if overwriting
    if (options.overwrite) {
      const tableNames = this.getTableNames().filter(name => !name.startsWith('_'));
      for (const tableName of tableNames) {
        this.unregister(tableName);
      }
    }
    
    // Register new tables
    this.registerFromDefinitions(data.tables);
    
    // Register relationships
    for (const relationship of data.relationships || []) {
      this.registerRelationship(relationship);
    }
  }

  // Private methods
  private createValidator(table: TableSchema): void {
    const shape: Record<string, z.ZodTypeAny> = {};
    
    for (const [columnName, column] of Object.entries(table.definition.columns)) {
      let validator: z.ZodTypeAny;
      
      switch (column.type) {
        case 'string':
        case 'text':
        case 'varchar':
          validator = z.string();
          if (column.type === 'varchar' && column.length) {
            validator = validator.max(column.length);
          }
          break;
        case 'integer':
        case 'bigint':
        case 'serial':
        case 'bigserial':
          validator = z.number().int();
          break;
        case 'float':
        case 'double':
          validator = z.number();
          break;
        case 'decimal':
        case 'numeric':
          validator = z.number();
          break;
        case 'boolean':
          validator = z.boolean();
          break;
        case 'date':
          validator = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
          break;
        case 'timestamp':
        case 'timestamptz':
          validator = z.date().or(z.string().datetime());
          break;
        case 'json':
        case 'jsonb':
          validator = z.any();
          break;
        case 'uuid':
          validator = z.string().uuid();
          break;
        case 'binary':
        case 'bytea':
          validator = z.instanceof(Buffer).or(z.string());
          break;
        default:
          validator = z.any();
      }
      
      if (column.nullable) {
        validator = validator.nullable();
      }
      
      shape[columnName] = validator;
    }
    
    this.validators.set(table.definition.name, z.object(shape));
  }

  private detectRelationships(table: TableSchema): void {
    const tableName = table.definition.name;
    
    // Detect foreign key relationships
    for (const [columnName, column] of Object.entries(table.definition.columns)) {
      if (column.references) {
        const relationship: Relationship = {
          id: `${tableName}.${columnName}->${column.references.table}.${column.references.column}`,
          sourceTable: tableName,
          sourceColumn: columnName,
          targetTable: column.references.table,
          targetColumn: column.references.column,
          type: 'foreign-key',
          onDelete: column.references.onDelete,
          onUpdate: column.references.onUpdate
        };
        
        this.registerRelationship(relationship);
      }
    }
    
    // Detect composite foreign keys
    if (table.definition.foreignKeys) {
      for (const fk of table.definition.foreignKeys) {
        const relationship: Relationship = {
          id: `${tableName}.${fk.columns.join('_')}->${fk.references.table}.${fk.references.columns.join('_')}`,
          sourceTable: tableName,
          sourceColumns: fk.columns,
          targetTable: fk.references.table,
          targetColumns: fk.references.columns,
          type: 'composite-foreign-key',
          onDelete: fk.onDelete,
          onUpdate: fk.onUpdate
        };
        
        this.registerRelationship(relationship);
      }
    }
  }

  private registerRelationship(relationship: Relationship): void {
    if (!this.relationships.has(relationship.sourceTable)) {
      this.relationships.set(relationship.sourceTable, []);
    }
    if (!this.relationships.has(relationship.targetTable)) {
      this.relationships.set(relationship.targetTable, []);
    }
    
    // Add to both source and target
    this.relationships.get(relationship.sourceTable)!.push(relationship);
    this.relationships.get(relationship.targetTable)!.push(relationship);
  }

  private detectCircularReferences(startTable: string, visited: Set<string> = new Set(), path: string[] = []): string[] {
    if (visited.has(startTable)) {
      return path.includes(startTable) ? [...path, startTable] : [];
    }
    
    visited.add(startTable);
    path.push(startTable);
    
    const relationships = this.getOutgoingRelationships(startTable);
    for (const rel of relationships) {
      if (rel.targetTable === startTable) {
        continue; // Skip self-references
      }
      
      const cycle = this.detectCircularReferences(rel.targetTable, visited, [...path]);
      if (cycle.length > 0) {
        return cycle;
      }
    }
    
    return [];
  }

  private validateTableDefinition(definition: TableDefinition): string[] {
    const errors: string[] = [];
    
    // Validate table name
    if (!definition.name || definition.name.trim() === '') {
      errors.push('Table name is required');
    }
    
    if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(definition.name)) {
      errors.push(`Invalid table name: ${definition.name}`);
    }
    
    // Validate columns
    if (Object.keys(definition.columns).length === 0) {
      errors.push('Table must have at least one column');
    }
    
    for (const [columnName, column] of Object.entries(definition.columns)) {
      if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(columnName)) {
        errors.push(`Invalid column name: ${columnName}`);
      }
      
      // Validate column definition
      if (!column.type) {
        errors.push(`Column ${columnName} must have a type`);
      }
    }
    
    // Validate primary key
    if (definition.primaryKey) {
      for (const pkColumn of definition.primaryKey) {
        if (!definition.columns[pkColumn]) {
          errors.push(`Primary key column ${pkColumn} does not exist`);
        }
      }
    }
    
    // Validate indexes
    if (definition.indexes) {
      for (const index of definition.indexes) {
        for (const column of index.columns) {
          if (!definition.columns[column]) {
            errors.push(`Index column ${column} does not exist`);
          }
        }
      }
    }
    
    return errors;
  }

  private generateAlterTableSQL(current: TableSchema, target: TableSchema): string | null {
    const statements: string[] = [];
    const currentDef = current.definition;
    const targetDef = target.definition;
    
    // Add new columns
    for (const [columnName, columnDef] of Object.entries(targetDef.columns)) {
      if (!currentDef.columns[columnName]) {
        statements.push(`ADD COLUMN ${this.generateColumnSQL(columnName, columnDef)}`);
      } else {
        // Check if column definition changed
        const currentColumn = currentDef.columns[columnName];
        if (this.columnsDiffer(currentColumn, columnDef)) {
          statements.push(`ALTER COLUMN ${this.quoteIdentifier(columnName)} TYPE ${this.getSQLType(columnDef)}`);
          
          if (currentColumn.nullable !== columnDef.nullable) {
            statements.push(`ALTER COLUMN ${this.quoteIdentifier(columnName)} ${columnDef.nullable ? 'DROP NOT NULL' : 'SET NOT NULL'}`);
          }
        }
      }
    }
    
    // Drop columns (with safety check)
    for (const [columnName, _] of Object.entries(currentDef.columns)) {
      if (!targetDef.columns[columnName]) {
        // Check if column has dependencies
        const hasRelationships = this.getRelationships(currentDef.name)
          .some(rel => rel.sourceColumn === columnName || rel.targetColumn === columnName);
        
        if (hasRelationships) {
          console.warn(`Cannot drop column ${columnName} from ${currentDef.name} because it has relationships`);
          continue;
        }
        
        statements.push(`DROP COLUMN ${this.quoteIdentifier(columnName)} CASCADE`);
      }
    }
    
    // Handle primary key changes
    const currentPK = current.getPrimaryKey();
    const targetPK = target.getPrimaryKey();
    if (JSON.stringify(currentPK) !== JSON.stringify(targetPK)) {
      if (currentPK.length > 0) {
        statements.push(`DROP CONSTRAINT ${this.quoteIdentifier(`${currentDef.name}_pkey`)}`);
      }
      if (targetPK.length > 0) {
        statements.push(`ADD PRIMARY KEY (${targetPK.map(c => this.quoteIdentifier(c)).join(', ')})`);
      }
    }
    
    if (statements.length === 0) {
      return null;
    }
    
    return `ALTER TABLE ${this.quoteIdentifier(currentDef.name)}\n  ${statements.join(',\n  ')};`;
  }

  private generateColumnSQL(name: string, column: ColumnDefinition): string {
    const parts: string[] = [
      this.quoteIdentifier(name),
      this.getSQLType(column)
    ];
    
    if (column.primaryKey && !column.autoIncrement) {
      parts.push('PRIMARY KEY');
    }
    
    if (!column.nullable) {
      parts.push('NOT NULL');
    }
    
    if (column.unique) {
      parts.push('UNIQUE');
    }
    
    if (column.default !== undefined) {
      parts.push(`DEFAULT ${this.formatDefault(column.default)}`);
    }
    
    if (column.check) {
      parts.push(`CHECK (${column.check})`);
    }
    
    return parts.join(' ');
  }

  private columnsDiffer(col1: ColumnDefinition, col2: ColumnDefinition): boolean {
    return col1.type !== col2.type ||
           (col1.length || 0) !== (col2.length || 0) ||
           (col1.precision || 0) !== (col2.precision || 0) ||
           (col1.scale || 0) !== (col2.scale || 0);
  }

  private getSQLType(col: ColumnDefinition): string {
    switch (col.type) {
      case 'string':
      case 'varchar':
        return col.length ? `VARCHAR(${col.length})` : 'VARCHAR(255)';
      case 'text':
        return 'TEXT';
      case 'integer':
        return 'INTEGER';
      case 'bigint':
        return 'BIGINT';
      case 'serial':
        return 'SERIAL';
      case 'bigserial':
        return 'BIGSERIAL';
      case 'float':
        return 'REAL';
      case 'double':
        return 'DOUBLE PRECISION';
      case 'decimal':
      case 'numeric':
        return col.precision && col.scale 
          ? `NUMERIC(${col.precision}, ${col.scale})`
          : 'NUMERIC';
      case 'boolean':
        return 'BOOLEAN';
      case 'date':
        return 'DATE';
      case 'timestamp':
        return 'TIMESTAMP';
      case 'timestamptz':
        return 'TIMESTAMPTZ';
      case 'json':
        return 'JSON';
      case 'jsonb':
        return 'JSONB';
      case 'uuid':
        return 'UUID';
      case 'binary':
      case 'bytea':
        return 'BYTEA';
      default:
        throw new Error(`Unknown column type: ${col.type}`);
    }
  }

  private formatDefault(value: any): string {
    if (value === null) return 'NULL';
    if (typeof value === 'string') {
      if (value.match(/^(CURRENT_TIMESTAMP|NOW\(\)|GEN_RANDOM_UUID\(\))/i)) {
        return value;
      }
      return `'${value.replace(/'/g, "''")}'`;
    }
    if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
    if (value instanceof Date) return `'${value.toISOString()}'`;
    if (typeof value === 'number') return String(value);
    if (typeof value === 'object') return `'${JSON.stringify(value)}'`;
    return String(value);
  }

  private quoteIdentifier(identifier: string): string {
    return `"${identifier.replace(/"/g, '""')}"`;
  }

  private toPascalCase(str: string): string {
    return str
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }

  private toTypeScriptType(columnType: ColumnType, nullable: boolean = false): string {
    const typeMap: Record<ColumnType, string> = {
      'string': 'string',
      'text': 'string',
      'varchar': 'string',
      'integer': 'number',
      'bigint': 'number',
      'serial': 'number',
      'bigserial': 'number',
      'float': 'number',
      'double': 'number',
      'decimal': 'number',
      'numeric': 'number',
      'boolean': 'boolean',
      'date': 'Timestamp',
      'timestamp': 'Timestamp',
      'timestamptz': 'Timestamp',
      'json': 'JSONValue',
      'jsonb': 'JSONValue',
      'uuid': 'UUID',
      'binary': 'Buffer',
      'bytea': 'Buffer'
    };
    
    const tsType = typeMap[columnType] || 'any';
    return nullable ? `${tsType} | null` : tsType;
  }
}

// Supporting types
export interface Relationship {
  id: string;
  sourceTable: string;
  sourceColumn?: string;
  sourceColumns?: string[];
  targetTable: string;
  targetColumn?: string;
  targetColumns?: string[];
  type: 'foreign-key' | 'composite-foreign-key' | 'many-to-many';
  onDelete?: 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION';
  onUpdate?: 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION';
  through?: {
    table: string;
    sourceColumn: string;
    targetColumn: string;
  };
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export interface SchemaExport {
  version: string;
  exportedAt: string;
  tables: TableDefinition[];
  relationships?: Relationship[];
}